### ISSUE TITLE
Update: Sign in with Tezos

### ISSUE THREAD

**Issue by jdsika** [The-Stack-Report/thestackreport.xyz#1]
Hi dev team,

I would like to inform you that the current version of SIWT has been overhauled and is now further developed in a new mono repository under the [old repo name](https://github.com/StakeNow/SIWT). The version you are using is still available under [SIWT-Deprecated](https://github.com/StakeNow/SIWT-Deprecated).

Here you can find the [link](https://forum.tezosagora.org/t/sign-in-with-tezos-siwt/4930) to the Agora article. We have added support for Discord verification which you can test right away in our StakeNow Discord!

Best regards
Carlo

**Comment by dp50mm** [comment]
Thanks for the pro-active outreach @jdsika, happy to see further progress on SIWT. Will keep a close eye to transition to the new implementation when its ready.
